### ISSUE TITLE
Estamos tendo um problema com ao integrar com o SDK

### ISSUE THREAD

**Issue by evenstaian** [starkbank/sdk-node#19]
starkbank/sdk/utils/rest.js:37
yield Object.assign(new resource['class'](entity), entity);
                  ^^^^^^

SyntaxError: Unexpected identifier

**Comment by LucasStarkBank** [comment]
Olá, @evenstaian .
Você poderia fornecer mais detalhes de como replicar esse erro?
Qual versão do Node você está usando?
Qual função foi chamada?

**Comment by czmarcos** [comment]
Também estou tendo mesmo problema, como conseguiu resolver?

node: v8.16.0
starkbank: ^2.4.0

```
/**
 * Responds to any HTTP request.
 *
 * @param {!express:Request} req HTTP request context.
 * @param {!express:Response} res HTTP response context.
 */
exports.startFunction = (req, res) => {

    const input = req.body;
    const starkbank = require('starkbank');

    let privateKeyContent = `
    -----BEGIN EC PARAMETERS-----
   abcdefg
    -----END EC PRIVATE KEY-----
    `;

    let project = new starkbank.Project({
        environment: 'sandbox',
        id: '12345',
        privateKey: privateKeyContent
    });

    (async() => {
        let balance = await starkbank.balance.get();
        console.log(balance);
    })();
        
};

```

/local-server/cloud-functions/starkbank/node_modules/starkbank/sdk/utils/rest.js:36
            yield Object.assign(new resource['class'](entity), entity);
                  ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/local-server/cloud-functions/starkbank/node_modules/starkbank/sdk/transaction/transaction.js:1:76)

**Comment by evenstaian** [comment]
Você precisa atualizar seu node.
