### ISSUE TITLE
Adicionar typings para TypeScript

### ISSUE THREAD

**Issue by rdsedmundo** [starkbank/sdk-node#56]
Hoje em dia já é praticamente padrão na indústria ter as declarações do TS. Facilita demais para o discovery de campos sem precisar ficar consultando a documentação da API toda hora, e também ajuda a encontrar usos incorretos de parâmetros e tratamento das respostas.

Outra opção melhor ainda do que só adicionar os typings seria converter o projeto para TS, aí não precisa ficar lembrando de manter os dois em sincronia. 😉

[Tipagens do SDK da Stripe como referência](https://github.com/stripe/stripe-node/blob/master/types/lib.d.ts).

**Comment by felixjb** [comment]
Algum update sobre essa issue? Seria muito legal ter os tipos do TypeScript no projeto

**Comment by mhamendes** [comment]
Também tenho interesse em uma atualização para essa issue.

**Comment by leandro-stark** [comment]
Olá, pessoal! Tudo bem?

Essa feature já está em nosso roadmap e em breve será disponibilizada!

Avisaremos vocês através dessa mesma issue.

Agradecemos pelo feedback!

**Comment by lunadis** [comment]
Opa, galera! temos alguma previsão de quando vai estar disponivel os types?

**Comment by leandro-stark** [comment]
Olá, pessoal!

A resolução desta issue já está liberada!

O sdk-node foi atualizado para a [v2.12.0](https://github.com/starkbank/sdk-node/releases/tag/v2.12.0).

Agradecemos o feedback!
