### ISSUE TITLE
Authenticating webhook issue

### ISSUE THREAD

**Issue by luisvinicius09** [starkbank/sdk-node#65]
Currently, I already finished integrating everything our company will be using thanks to the great documentation. But, I'm having problems authenticating webhooks.

According to [README docs](https://github.com/starkbank/sdk-node#process-webhook-events), I'm trying to use the method `starkbank.event.parse()`, but it's not working like it is supposed to.

The docs say to use it like this:
```node
  let event = await starkbank.event.parse({
      content: req.body.toString(),
      signature: req.headers['digital-signature']
  });
```
Though `req.body.toString()` will not work, it will always return this error:
![image](https://user-images.githubusercontent.com/60414217/152428679-35f6b045-34a0-4a28-8ee9-3816715db62f.png)

The correct way of doing it is using `content: JSON.stringify(req.body)`, according to the `parse()` method description:
![image](https://user-images.githubusercontent.com/60414217/152428975-eb75f503-ef9f-4fb7-a83a-5e8eddfb2e03.png)

> Everything above this is just my input towards the improvement of the documentation.

#### This is my currently implementation:
![image](https://user-images.githubusercontent.com/60414217/152429421-cefaa10f-d5f2-4f46-8ca4-739f33916003.png)

#### It returns the error correctly, but it's not supposed to return the error, since there is almost no difference between the implementations, I even tested with a brand new express boilerplate, and still returns the error:
![image](https://user-images.githubusercontent.com/60414217/152430014-8f5cda2c-2f3f-43e1-bdf5-f26eb65069d3.png)

## Are there any problems with my implementation? I'm not doing anything crazy, but I might be missing something.

If more information is needed, I'll be happy to provide it.

## #Edit
I'm aware that there is another way of authenticating it, but it would be very handy to use this method. 🚀

**Comment by joaogpw-stark** [comment]
Hello, Vinicius! Thank you for your message!

When parsing an Event, the content must be sent exactly as it is received from our Webhook.

If any byte of the content is changed, it's SHA256 hash, used to generate the signature, also changes, breaking the provided signature.

We're not sure what "IRequest" does to the content but it should't alter the content in any way (with prettifiers, for example) or you will receive this error.

If you have any additional questions, don't hesitate to ask!

Best,

**Comment by luisvinicius09** [comment]
Well, "IRequest" is simply the type that we use for the request, because we are using Typescript, it should not modify the request in anyways. But, I still tried with a fresh new API and still got the same results:

- As you can see, this is the setup file for the API, and the only thing that is looking at the request is `express.json()`:
![Code_DCP37vtM4H](https://user-images.githubusercontent.com/60414217/152702809-b4fcedec-fa47-400e-89da-254155423711.png)


- Here is the router file:
![Code_8Sf1K5KLil](https://user-images.githubusercontent.com/60414217/152702823-39c36e9f-e355-45d8-b1c6-566d33de8b0d.png)

- And here is the results:
![Code_s0eW9vM0Td](https://user-images.githubusercontent.com/60414217/152702839-33b31c02-929b-431b-806b-cda47f59cbb5.png)


### Like I said before, I've seen that there is another way of authenticating the Webhook, by using the [ecdsa-node](https://github.com/starkbank/ecdsa-node) dependency, in which I'm already working on a solution to implement. But it just would be very handy to have the method working on our side and one less dependency.

If more information is needed on my side, I'll be happy to provide it!

Regards

**Comment by rcmstark** [comment]
At your router file, line 39, the JSON.stringfy is changing the body data. You should use the exactly raw body data our API is returning to you. Any change on it will make the signature not match.

**Comment by luisvinicius09** [comment]
Well, then it will go back to throwing a `SyntaxError`:

![image](https://user-images.githubusercontent.com/60414217/152718889-850ea5d0-0e37-4db7-9e7b-13064cac3dc2.png)

For this reason, I assumed that `stringify` was needed.
#

### But, now I took another look at the documentation and just realized that I'm forced to receive the request in its raw form:

![image](https://user-images.githubusercontent.com/60414217/152719157-60db9a52-9ef1-4b8a-80a5-0b053c67e425.png)

And for this reason, I won't be able to use the method because it will affect our API's performance and I'll stick with a raw authentication using the [ecdsa-node](https://github.com/starkbank/ecdsa-node) dependency to verify the signature.

I appreciate the help and your time!
