### ISSUE TITLE
@types/starkbank development package

### ISSUE THREAD

**Issue by rodrigo-voll** [starkbank/sdk-node#78]
It's possible to provide the **@types/starkbank** development package or built-in the ts types in the dist?

HOWTO to create development package, can be read in github for the repository for high quality TypeScript type definitions.

[https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

or built-in the types in the distribution

**Comment by xavier-stark** [comment]
Hi, rodrigo-voll!

We released a new SDK version containing a "types" folder to support typescript types.

If you have any questions, do not hesitate to ask!

Best,
