### ISSUE TITLE
`transfer.query` Não retorna dados

### ISSUE THREAD

**Issue by quantodaniel** [starkbank/sdk-node#84]
Ambiente: 
- sandbox

Versão:
- 2.13.2

Descrição:
- Criei transferência utilizando `starkbank.transfer.create(...)` e guardei id retornado como transferId para consulta posterior.
- A consulta utilizando id `starkbank.transfer.get(transferId)`, e a visualização no painel de controle está funcionando normalmente.

Problema:
- Ao buscar as transferências utilizando `starkbank.transfer.query()`, com ou sem filtros, sempre retorna vazio. 

Resultado esperado:
- `starkbank.transfer.query()` sem filtros deveria ter o mesmo comportamento de outras apis, como de instituições, e retornar todas as transferências criadas, ou até um limite pré definido.
- `starkbank.transfer.query(...)` com filtros relacionados aos dados já existentes deveria voltar uma lista com as transferências.

**Comment by quantodaniel** [comment]
Também seria interessante filtro por externalId.

**Comment by xavier-stark** [comment]
Olá, @quantodaniel!

Realizamos o procedimento mencionado utilizando o SDK versão 2.13.2, no ambiente de Sandbox da seguinte forma:
```
let transfers = await starkbank.transfer.query({
  ids: ['5279523557867520', '6473796391272448']
});

for await (let transfer of transfers) {
  console.log(transfer);
}
```
Entretanto, o erro mencionado não ocorreu.

Vale ressaltar que o retorno do método query, é um objeto Generator. Sendo assim, é necessário iterar o objeto Generator para obter os dados deste, conforme o exemplo acima.

Qualquer dúvida, estamos à disposição!

Abraços!
