### ISSUE TITLE
[Bug] transfer.pdf method sending wrong parameters

### ISSUE THREAD

**Issue by Jesinski** [starkbank/sdk-node#90]
There's a bug on the following line:

https://github.com/starkbank/sdk-node/blob/c10982146a294d1b0ff34e5e0cb70fb1fa0dd819/sdk/transfer/transfer.js#L150

The method is sending the user as options to getPdf function, which breaks the preProcess latter, also it adds the user's private key to the URL (which is not cool).

It is an easy fix, it's just missing a empty object on the function call, so I'll open a PR for it.

Thanks.
Gustavo Jesinski

**Comment by kessler-oliveira** [comment]
I had the same issue

**Comment by leandro-stark** [comment]
Hi, everyone!

We released a new Node SDK version,  [v2.17.0](https://github.com/starkbank/sdk-node/releases/tag/v2.17.0), where this issue was solved.

If you have any questions, do not hesitate do ask!

Best,
